import json
import os

translations = {
    "pt-BR": {
        "login_btn": "Entrar",
        "badge_free": "FREE",
        "badge_pro": "PRO",
        "plan_free": "Plano: Free",
        "plan_pro": "Plano: Pro",
        "upgrade_btn": "Upgrade para Pro",
        "logout_btn": "Sair",
        "tab_login": "Entrar",
        "tab_signup": "Criar conta",
        "email_label": "Email",
        "password_label": "Senha",
        "confirm_password_label": "Confirmar Senha",
        "submit_login": "Entrar",
        "submit_signup": "Criar conta",
        "forgot_password": "Esqueci minha senha?",
        "or": "ou",
        "google_login": "Entrar com Google",
        "err_invalid_email": "Email inválido.",
        "err_user_not_found": "Usuário não encontrado.",
        "err_wrong_password": "Senha incorreta.",
        "err_email_in_use": "Email já está em uso.",
        "err_weak_password": "A senha deve ter pelo menos 8 caracteres.",
        "err_default": "Erro na autenticação. Tente novamente.",
        "reset_email_sent": "Email de recuperação enviado."
    },
    "en-US": {
        "login_btn": "Log in",
        "badge_free": "FREE",
        "badge_pro": "PRO",
        "plan_free": "Plan: Free",
        "plan_pro": "Plan: Pro",
        "upgrade_btn": "Upgrade to Pro",
        "logout_btn": "Log out",
        "tab_login": "Log in",
        "tab_signup": "Sign up",
        "email_label": "Email",
        "password_label": "Password",
        "confirm_password_label": "Confirm Password",
        "submit_login": "Log in",
        "submit_signup": "Create account",
        "forgot_password": "Forgot password?",
        "or": "or",
        "google_login": "Continue with Google",
        "err_invalid_email": "Invalid email.",
        "err_user_not_found": "User not found.",
        "err_wrong_password": "Wrong password.",
        "err_email_in_use": "Email already in use.",
        "err_weak_password": "Password must be at least 8 characters.",
        "err_default": "Authentication error. Try again.",
        "reset_email_sent": "Recovery email sent."
    },
    "es": {
        "login_btn": "Entrar",
        "badge_free": "FREE",
        "badge_pro": "PRO",
        "plan_free": "Plan: Free",
        "plan_pro": "Plan: Pro",
        "upgrade_btn": "Actualizar a Pro",
        "logout_btn": "Salir",
        "tab_login": "Entrar",
        "tab_signup": "Registrarse",
        "email_label": "Correo electrónico",
        "password_label": "Contraseña",
        "confirm_password_label": "Confirmar Contraseña",
        "submit_login": "Entrar",
        "submit_signup": "Crear cuenta",
        "forgot_password": "¿Olvidaste tu contraseña?",
        "or": "o",
        "google_login": "Entrar con Google",
        "err_invalid_email": "Correo inválido.",
        "err_user_not_found": "Usuario no encontrado.",
        "err_wrong_password": "Contraseña incorrecta.",
        "err_email_in_use": "El correo ya está en uso.",
        "err_weak_password": "La contraseña debe tener al menos 8 caracteres.",
        "err_default": "Error de autenticación. Intenta de nuevo.",
        "reset_email_sent": "Correo de recuperación enviado."
    },
    "fr": {
        "login_btn": "Se connecter",
        "badge_free": "GRATUIT",
        "badge_pro": "PRO",
        "plan_free": "Forfait: Gratuit",
        "plan_pro": "Forfait: Pro",
        "upgrade_btn": "Passer au Pro",
        "logout_btn": "Se déconnecter",
        "tab_login": "Se connecter",
        "tab_signup": "S'inscrire",
        "email_label": "E-mail",
        "password_label": "Mot de passe",
        "confirm_password_label": "Confirmer le mot de passe",
        "submit_login": "Se connecter",
        "submit_signup": "Créer un compte",
        "forgot_password": "Mot de passe oublié ?",
        "or": "ou",
        "google_login": "Continuer avec Google",
        "err_invalid_email": "E-mail invalide.",
        "err_user_not_found": "Utilisateur introuvable.",
        "err_wrong_password": "Mot de passe incorrect.",
        "err_email_in_use": "Cet e-mail est déjà utilisé.",
        "err_weak_password": "Le mot de passe doit contenir au moins 8 caractères.",
        "err_default": "Erreur d'authentification. Réessayez.",
        "reset_email_sent": "E-mail de récupération envoyé."
    },
    "de": {
        "login_btn": "Anmelden",
        "badge_free": "GRATIS",
        "badge_pro": "PRO",
        "plan_free": "Plan: Gratis",
        "plan_pro": "Plan: Pro",
        "upgrade_btn": "Auf Pro upgraden",
        "logout_btn": "Abmelden",
        "tab_login": "Anmelden",
        "tab_signup": "Registrieren",
        "email_label": "E-Mail",
        "password_label": "Passwort",
        "confirm_password_label": "Passwort bestätigen",
        "submit_login": "Anmelden",
        "submit_signup": "Konto erstellen",
        "forgot_password": "Passwort vergessen?",
        "or": "oder",
        "google_login": "Mit Google fortfahren",
        "err_invalid_email": "Ungültige E-Mail.",
        "err_user_not_found": "Benutzer nicht gefunden.",
        "err_wrong_password": "Falsches Passwort.",
        "err_email_in_use": "E-Mail wird bereits verwendet.",
        "err_weak_password": "Passwort muss mindestens 8 Zeichen lang sein.",
        "err_default": "Authentifizierungsfehler. Bitte erneut versuchen.",
        "reset_email_sent": "Wiederherstellungs-E-Mail gesendet."
    },
    "ja": {
        "login_btn": "ログイン",
        "badge_free": "無料",
        "badge_pro": "PRO",
        "plan_free": "プラン: 無料",
        "plan_pro": "プラン: Pro",
        "upgrade_btn": "Proにアップグレード",
        "logout_btn": "ログアウト",
        "tab_login": "ログイン",
        "tab_signup": "サインアップ",
        "email_label": "メールアドレス",
        "password_label": "パスワード",
        "confirm_password_label": "パスワードの確認",
        "submit_login": "ログイン",
        "submit_signup": "アカウント作成",
        "forgot_password": "パスワードをお忘れですか？",
        "or": "または",
        "google_login": "Googleで続行",
        "err_invalid_email": "無効なメールアドレスです。",
        "err_user_not_found": "ユーザーが見つかりません。",
        "err_wrong_password": "パスワードが間違っています。",
        "err_email_in_use": "このメールアドレスは既に使用されています。",
        "err_weak_password": "パスワードは8文字以上である必要があります。",
        "err_default": "認証エラー。もう一度お試しください。",
        "reset_email_sent": "再設定メールを送信しました。"
    },
    "ko": {
        "login_btn": "로그인",
        "badge_free": "무료",
        "badge_pro": "PRO",
        "plan_free": "플랜: 무료",
        "plan_pro": "플랜: Pro",
        "upgrade_btn": "Pro로 업그레이드",
        "logout_btn": "로그아웃",
        "tab_login": "로그인",
        "tab_signup": "가입하기",
        "email_label": "이메일",
        "password_label": "비밀번호",
        "confirm_password_label": "비밀번호 확인",
        "submit_login": "로그인",
        "submit_signup": "계정 생성",
        "forgot_password": "비밀번호를 잊으셨나요?",
        "or": "또는",
        "google_login": "Google로 계속",
        "err_invalid_email": "유효하지 않은 이메일입니다.",
        "err_user_not_found": "사용자를 찾을 수 없습니다.",
        "err_wrong_password": "잘못된 비밀번호입니다.",
        "err_email_in_use": "이미 사용 중인 이메일입니다.",
        "err_weak_password": "비밀번호는 8자 이상이어야 합니다.",
        "err_default": "인증 오류. 다시 시도하세요.",
        "reset_email_sent": "복구 이메일이 전송되었습니다."
    },
    "hi": {
        "login_btn": "लॉग इन",
        "badge_free": "मुफ़्त",
        "badge_pro": "PRO",
        "plan_free": "योजना: मुफ़्त",
        "plan_pro": "योजना: Pro",
        "upgrade_btn": "Pro में अपग्रेड करें",
        "logout_btn": "लॉग आउट",
        "tab_login": "लॉग इन",
        "tab_signup": "साइन अप",
        "email_label": "ईमेल",
        "password_label": "पासवर्ड",
        "confirm_password_label": "पासवर्ड की पुष्टि करें",
        "submit_login": "लॉग इन",
        "submit_signup": "खाता बनाएं",
        "forgot_password": "पासवर्ड भूल गए?",
        "or": "या",
        "google_login": "Google के साथ जारी रखें",
        "err_invalid_email": "अमान्य ईमेल।",
        "err_user_not_found": "उपयोगकर्ता नहीं मिला।",
        "err_wrong_password": "गलत पासवर्ड।",
        "err_email_in_use": "ईमेल पहले से ही उपयोग में है।",
        "err_weak_password": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए।",
        "err_default": "प्रमाणीकरण त्रुटि। पुन: प्रयास करें।",
        "reset_email_sent": "रिकवरी ईमेल भेजा गया।"
    },
    "ar": {
        "login_btn": "تسجيل الدخول",
        "badge_free": "مجاني",
        "badge_pro": "PRO",
        "plan_free": "الخطة: مجاني",
        "plan_pro": "الخطة: Pro",
        "upgrade_btn": "الترقية إلى Pro",
        "logout_btn": "تسجيل الخروج",
        "tab_login": "تسجيل الدخول",
        "tab_signup": "إنشاء حساب",
        "email_label": "البريد الإلكتروني",
        "password_label": "كلمة المرور",
        "confirm_password_label": "تأكيد كلمة المرور",
        "submit_login": "تسجيل الدخول",
        "submit_signup": "إنشاء حساب",
        "forgot_password": "هل نسيت كلمة المرور؟",
        "or": "أو",
        "google_login": "المتابعة باستخدام Google",
        "err_invalid_email": "بريد إلكتروني غير صالح.",
        "err_user_not_found": "المستخدم غير موجود.",
        "err_wrong_password": "كلمة مرور خاطئة.",
        "err_email_in_use": "البريد الإلكتروني مستخدم بالفعل.",
        "err_weak_password": "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.",
        "err_default": "خطأ في المصادقة. حاول مرة أخرى.",
        "reset_email_sent": "تم إرسال بريد الاسترداد الإلكتروني."
    }
}

for lang, auth_data in translations.items():
    file_path = f"lang/{lang}.json"
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        data["auth"] = auth_data
        
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            
print("Successfully updated 9 language files.")
